name: 🚀 Deploy Frontend Vue 3 + Bootstrap 5

# Déclenche le workflow uniquement sur les pushes sur la branche main
on:
  push:
    branches:
      - main

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Installer les dépendances frontend
      - name: Install frontend dependencies
        run: |
          npm ci

      # 4️⃣ Construire le frontend
      - name: Build frontend
        run: |
          npm run build

      # 4️⃣ bis – Créer le .htaccess pour SPA
      - name: Create .htaccess for SPA routing
        run: |
          cat <<EOT > dist/.htaccess
          # Activer la réécriture d'URL
          RewriteEngine On

          # Si la requête correspond à un fichier ou un répertoire existant, Apache ne réécrit pas l'URL
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d

          # Réécrire toutes les requêtes vers index.html pour gérer la SPA (Single Page Application)
          RewriteRule ^ index.html [QSA,L]

          # Redirection HTTP vers HTTPS (optionnel)
          # Si ton site utilise HTTPS, décommente cette section pour forcer la redirection vers HTTPS
          # RewriteCond %{HTTPS} off
          # RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

          # Cache des fichiers statiques pour améliorer la performance
          <FilesMatch "\.(jpg|jpeg|png|gif|css|js|woff|woff2|ttf|eot|svg|otf)$">
          Header set Cache-Control "public, max-age=31536000, immutable"
          </FilesMatch>

          # Gérer la sécurité en limitant l'accès à certains fichiers
          <FilesMatch "\.(htaccess|htpasswd|ini|log|sh|git)">
          Order Allow,Deny
          Deny from all
          </FilesMatch>

          # Sécuriser les en-têtes HTTP (optionnel mais recommandé)
          Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
          Header always set X-Content-Type-Options "nosniff"
          Header always set X-Frame-Options "SAMEORIGIN"
          Header always set X-XSS-Protection "1; mode=block"
          Header always set Referrer-Policy "strict-origin-when-cross-origin"

          # Prévenir les attaques de type clickjacking
          Header always set X-Frame-Options "DENY"

          # php -- BEGIN cPanel-generated handler, do not edit
          # Set the “ea-php81” package as the default “PHP” programming language.
          <IfModule mime_module>
            AddHandler application/x-httpd-ea-php81 .php .php8 .phtml
          </IfModule>
          # php -- END cPanel-generated handler, do not edit

          EOT

      # 5️⃣ Déployer sur cPanel via SFTP
      - name: Deploy Frontend via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_HOST }}          # ton serveur cPanel
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}   # clé SSH pour le serveur
          port: ${{ secrets.SFTP_PORT }}         # souvent 22 ou ton port personnalisé
          source: "dist/*"             # dossier généré par npm run build
          target: "/home/axproo/public_html/vue_dashboard"   # dossier cible sur le serveur
          rm: false                              # supprime les anciens fichiers
          overwrite: true                        # écrase uniquement les fichiers modifiés
          debug: true                            # logs détaillés pour le débogage
